id = superkid
name = Super Kid
mainURL = https://sianhung-superkid.surge.sh/
icon = /Users/Richard/.gemini/antigravity-ide/scratch/icon-512.png

allowSubdomains = true
requireDoubleBackToExit = true

enableExternalLinks = true
openExternalLinksInBrowser = true
confirmOpenInBrowser = true

allowOpenMobileApp = false
forceLandscapeMode = false
edgeToEdge = true
deeplink = sianhung-superkid.surge.sh
