id = bingo_movies
name = Bingo Movies
mainURL = https://vod-saas-kappa.vercel.app/
icon = /Users/Richard/vod-saas/public/icon-512x512.png

allowSubdomains = true
requireDoubleBackToExit = true
enableExternalLinks = true
openExternalLinksInBrowser = true
confirmOpenInBrowser = true
edgeToEdge = true
deeplink = vod-saas-kappa.vercel.app
